-- ============================================================
-- Development seed data — run AFTER schema.sql
-- Creates a shared exercise library. Trainer/client data is
-- created via the app UI or Supabase Auth dashboard.
-- ============================================================

INSERT INTO exercises (name, muscle_group, category) VALUES
  -- Chest
  ('Bench Press',            'Chest',     'strength'),
  ('Incline Bench Press',    'Chest',     'strength'),
  ('Push-Up',                'Chest',     'strength'),
  ('Cable Fly',              'Chest',     'strength'),
  -- Back
  ('Deadlift',               'Back',      'strength'),
  ('Pull-Up',                'Back',      'strength'),
  ('Barbell Row',            'Back',      'strength'),
  ('Lat Pulldown',           'Back',      'strength'),
  ('Seated Cable Row',       'Back',      'strength'),
  -- Shoulders
  ('Overhead Press',         'Shoulders', 'strength'),
  ('Lateral Raise',          'Shoulders', 'strength'),
  ('Face Pull',              'Shoulders', 'strength'),
  -- Arms
  ('Barbell Curl',           'Arms',      'strength'),
  ('Tricep Pushdown',        'Arms',      'strength'),
  ('Hammer Curl',            'Arms',      'strength'),
  ('Skull Crusher',          'Arms',      'strength'),
  -- Legs
  ('Squat',                  'Legs',      'strength'),
  ('Romanian Deadlift',      'Legs',      'strength'),
  ('Leg Press',              'Legs',      'strength'),
  ('Leg Curl',               'Legs',      'strength'),
  ('Leg Extension',          'Legs',      'strength'),
  ('Calf Raise',             'Legs',      'strength'),
  ('Lunges',                 'Legs',      'strength'),
  -- Core
  ('Plank',                  'Core',      'strength'),
  ('Crunch',                 'Core',      'strength'),
  ('Cable Crunch',           'Core',      'strength'),
  -- Cardio
  ('Treadmill Run',          NULL,        'cardio'),
  ('Rowing Machine',         NULL,        'cardio'),
  ('Cycling',                NULL,        'cardio'),
  ('Jump Rope',              NULL,        'cardio')
ON CONFLICT (name) DO NOTHING;

-- ─── Extended Exercise Library ────────────────────────────────
INSERT INTO exercises (name, muscle_group, category) VALUES
  -- Glutes
  ('Glute Bridge',                        'Glutes',    'strength'),
  ('Glute Bridge Hold',                   'Glutes',    'strength'),
  ('Glute Bridge (Pulsing)',              'Glutes',    'strength'),
  ('Single-Leg Bridge',                   'Glutes',    'strength'),
  -- Legs
  ('Air Squat',                           'Legs',      'strength'),
  ('Box Squat',                           'Legs',      'strength'),
  ('Reverse Lunge',                       'Legs',      'strength'),
  ('Single-Leg Reach (Bulg Squat)',       'Legs',      'strength'),
  ('Step-ups/Weighted',                   'Legs',      'strength'),
  ('Squat Press (DB/Bar)',                'Legs',      'strength'),
  ('Lateral Lunge',                       'Legs',      'strength'),
  ('Wall Sit',                            'Legs',      'strength'),
  ('Single-Leg Step-Up',                  'Legs',      'strength'),
  ('Box Jump',                            'Legs',      'cardio'),
  ('Jump Squats',                         'Legs',      'cardio'),
  ('Box Step-ups',                        'Legs',      'strength'),
  ('Walking Lunges',                      'Legs',      'strength'),
  ('DB Split Squat',                      'Legs',      'strength'),
  ('Leg Press + Leg Machines',            'Legs',      'strength'),
  ('Hamstring Curl',                      'Legs',      'strength'),
  ('DB Step-ups',                         'Legs',      'strength'),
  ('Wall Sits (Weighted)',                'Legs',      'strength'),
  ('Goblet Lateral Lunge',               'Legs',      'strength'),
  ('Lunge with Twist',                    'Legs',      'strength'),
  ('Skater Jumps',                        'Legs',      'cardio'),
  ('Single-Leg Hops',                     'Legs',      'cardio'),
  ('Lateral Bounds',                      'Legs',      'cardio'),
  ('DB Goblet Squat',                     'Legs',      'strength'),
  ('RDL',                                 'Legs',      'strength'),
  ('RDL (Dumbbells)',                     'Legs',      'strength'),
  ('KB Deadlift',                         'Legs',      'strength'),
  ('Pilates Squat + Squat',              'Legs',      'strength'),
  -- Chest
  ('Incline Push-up',                     'Chest',     'strength'),
  ('Floor Press + Mod Push-up',           'Chest',     'strength'),
  ('Tempo Push-ups',                      'Chest',     'strength'),
  ('T-Pushups',                           'Chest',     'strength'),
  ('Spiderman Push-ups',                  'Chest',     'strength'),
  ('Diamond + Wide Pushups',             'Chest',     'strength'),
  ('DB Bench Press',                      'Chest',     'strength'),
  ('DB Incline Press',                    'Chest',     'strength'),
  ('Chest Pass (Med Ball)',               'Chest',     'strength'),
  ('Push-up (Weighted)',                  'Chest',     'strength'),
  ('Dips',                                'Chest',     'strength'),
  ('Dips/Band Flyes',                    'Chest',     'strength'),
  -- Back
  ('Pull up/Lat Pulldown',               'Back',      'strength'),
  ('Mid Row',                             'Back',      'strength'),
  ('Cable Pullover',                      'Back',      'strength'),
  ('Scapular Pull-up',                   'Back',      'strength'),
  ('Scapular Push-ups',                  'Back',      'strength'),
  ('BW Back Extensions',                 'Back',      'strength'),
  ('Chin-up Negatives',                  'Back',      'strength'),
  ('DB Renegade Row',                     'Back',      'strength'),
  ('Cable Squat Row',                     'Back',      'strength'),
  -- Shoulders
  ('Cable Face Pulls',                    'Shoulders', 'strength'),
  ('DB Overhead Press',                   'Shoulders', 'strength'),
  ('Cable/Band Lateral Raise',           'Shoulders', 'strength'),
  ('Pike Push-ups',                       'Shoulders', 'strength'),
  -- Arms
  ('Towel Curls',                         'Arms',      'strength'),
  ('Bicep Curls',                         'Arms',      'strength'),
  ('Box Dips (Assist)',                   'Arms',      'strength'),
  -- Core
  ('Plank (Variations)',                  'Core',      'strength'),
  ('Plank Taps',                          'Core',      'strength'),
  ('Plank-to-Pushup',                    'Core',      'strength'),
  ('Side Planks',                         'Core',      'strength'),
  ('Side Plank Dips',                    'Core',      'strength'),
  ('Plank with Knee-to-Elbow',           'Core',      'strength'),
  ('Plank (Weighted)',                    'Core',      'strength'),
  ('Plank with Row',                      'Core',      'strength'),
  ('Plank Shoulder Taps',                'Core',      'strength'),
  ('Plank In and Outs',                  'Core',      'strength'),
  ('Plank Jacks',                         'Core',      'cardio'),
  ('Bicycle Crunches',                    'Core',      'strength'),
  ('Russian Twists',                      'Core',      'strength'),
  ('Decline Russian Twists',             'Core',      'strength'),
  ('V-Ups',                               'Core',      'strength'),
  ('V-Ups/Knee Raises',                  'Core',      'strength'),
  ('Flutter Kicks',                       'Core',      'strength'),
  ('Reverse Crunch',                      'Core',      'strength'),
  ('Weighted Sit-up',                     'Core',      'strength'),
  ('Deadbug (Weighted)',                  'Core',      'strength'),
  ('Deadbugs',                            'Core',      'strength'),
  ('Pallof Press',                        'Core',      'strength'),
  ('Cable Torso Rotations',              'Core',      'strength'),
  ('Static Squat Cable Torso Rotations', 'Core',      'strength'),
  ('Cable Woodchops',                     'Core',      'strength'),
  ('Hanging Leg Raises',                 'Core',      'strength'),
  ('Landmine Rotation',                   'Core',      'strength'),
  ('Windshields/Alternate Knee Raises',  'Core',      'strength'),
  ('Medicine Ball Rotational Toss',      'Core',      'strength'),
  ('Center Decline',                      'Core',      'strength'),
  ('Teapots',                             'Core',      'strength'),
  ('Single Leg Decline',                 'Core',      'strength'),
  ('Knee/Leg Raises',                    'Core',      'strength'),
  ('Knee to Elbows',                      'Core',      'strength'),
  ('Toe Taps',                            'Core',      'strength'),
  -- Full Body / Compound
  ('Landmine',                            NULL,        'strength'),
  ('Bear Crawl',                          NULL,        'strength'),
  ('Inchworm Push-Up',                   NULL,        'strength'),
  ('Ball Squat Toss',                     NULL,        'strength'),
  ('Med Ball Slams',                      NULL,        'strength'),
  ('Med Ball Overhead Hold',             NULL,        'strength'),
  ('Wall Balls',                          NULL,        'strength'),
  ('Burpee DB Press',                     NULL,        'strength'),
  ('Suitcase Carry (L/R)',               NULL,        'strength'),
  ('Farmer''s Walk',                      NULL,        'strength'),
  ('Squat Thrusts',                       NULL,        'cardio'),
  -- Cardio
  ('Mountain Climbers + Air Squats',     NULL,        'cardio'),
  ('Mountain Climbers',                   NULL,        'cardio'),
  ('Mountain Climber Burpee',            NULL,        'cardio'),
  ('In-Out Jumping Jacks',               NULL,        'cardio'),
  ('High Knees (s)',                      NULL,        'cardio'),
  ('Butt Kicks (s)',                      NULL,        'cardio'),
  ('Rope Ladder Broad Jumps',            NULL,        'cardio'),
  ('Jumping Jacks (s)',                   NULL,        'cardio'),
  ('Shuttle Runs (yd)',                   NULL,        'cardio'),
  ('Speed Skaters',                       NULL,        'cardio'),
  ('Burpees',                             NULL,        'cardio'),
  ('Ice Skater Steps',                    NULL,        'cardio'),
  -- Flexibility / Mobility
  ('Cobra Stretch',                       NULL,        'flexibility'),
  ('Hip Circles',                         NULL,        'flexibility')
ON CONFLICT (name) DO NOTHING;
