// ============================================================
// Workout Templates — sourced from workout_templates.csv
// Structured as static data; exercise names are matched
// against the live exercises table when a template is loaded.
// ============================================================

export type WorkoutTemplate = {
  id: string;
  name: string;
  exerciseNames: string[];
};

export const WORKOUT_TEMPLATES: WorkoutTemplate[] = [
  {
    id: 'P1-A',
    name: 'Workout A: Push Focus',
    exerciseNames: [
      'Air Squat',
      'Glute Bridge',
      'Incline Push-up',
      'Floor Press + Mod Push-up',
      'Dips',
      'Plank (Variations)',
      'Mountain Climbers + Air Squats',
      'Cobra Stretch',
      'Bear Crawl',
      'Glute Bridge Hold',
    ],
  },
  {
    id: 'P1-B',
    name: 'Workout B: Pull Focus',
    exerciseNames: [
      'Reverse Lunge',
      'Single-Leg Reach (Bulg Squat)',
      'Pull up/Lat Pulldown',
      'Mid Row',
      'RDL',
      'Cable Pullover',
      'Towel Curls',
      'Hammer Curl',
      'Bear Crawl',
      'Glute Bridge (Pulsing)',
    ],
  },
  {
    id: 'P1-C',
    name: 'Workout C: Stability',
    exerciseNames: [
      'Box Squat',
      'Step-ups/Weighted',
      'Landmine',
      'Squat Press (DB/Bar)',
      'Cable Squat Row',
      'Cable Torso Rotations',
      'Scapular Push-ups',
      'Scapular Pull-up',
      'Plank Taps',
      'BW Back Extensions',
    ],
  },
  {
    id: 'P1-D',
    name: 'Workout D: Lateral/Total',
    exerciseNames: [
      'Lateral Lunge',
      'Wall Sit',
      'Plank-to-Pushup',
      'Box Jump',
      'Side Planks',
      'Ball Squat Toss',
      'Single-Leg Step-Up',
      'Hip Circles',
      'Mountain Climbers',
      'In-Out Jumping Jacks',
    ],
  },
  {
    id: 'P2-A',
    name: 'Workout A: Push Focus (P2)',
    exerciseNames: [
      'Skater Jumps',
      'Jump Squats',
      'Tempo Push-ups',
      'Chest Pass (Med Ball)',
      'Plank Jacks',
      'Flutter Kicks',
      'T-Pushups',
      'High Knees (s)',
      'Box Jump',
      'Deadbug (Weighted)',
    ],
  },
  {
    id: 'P2-B',
    name: 'Workout B: Pull Focus (P2)',
    exerciseNames: [
      'Box Step-ups',
      'Walking Lunges',
      'Chin-up Negatives',
      'Med Ball Slams',
      'Mountain Climbers',
      'Bicycle Crunches',
      'Cable Face Pulls',
      'Butt Kicks (s)',
      'Single-Leg Hops',
      'Plank (Weighted)',
    ],
  },
  {
    id: 'P2-C',
    name: 'Workout C: Shoulder Focus (P2)',
    exerciseNames: [
      'Rope Ladder Broad Jumps',
      'Lateral Bounds',
      'Med Ball Overhead Hold',
      'Wall Balls',
      'Russian Twists',
      'Static Squat Cable Torso Rotations',
      'Pike Push-ups',
      'Jumping Jacks (s)',
      'Pilates Squat + Squat',
      'Side Plank Dips',
    ],
  },
  {
    id: 'P2-D',
    name: 'Workout D: Agility/Total (P2)',
    exerciseNames: [
      'Shuttle Runs (yd)',
      'Speed Skaters',
      'V-Ups/Knee Raises',
      'Burpees',
      'Spiderman Push-ups',
      'Plank with Knee-to-Elbow',
      'Mountain Climber Burpee',
      'Ice Skater Steps',
      'Squat Thrusts',
      'Deadlift',
    ],
  },
  {
    id: 'P3-A',
    name: 'Workout A: Chest/Push (P3)',
    exerciseNames: [
      'DB Goblet Squat',
      'RDL (Dumbbells)',
      'DB Bench Press',
      'DB Incline Press',
      'Deadbug (Weighted)',
      'Pallof Press',
      'Dips/Band Flyes',
      'Inchworm Push-Up',
      'Calf Raise',
      'Weighted Sit-up',
    ],
  },
  {
    id: 'P3-B',
    name: 'Workout B: Back/Pull (P3)',
    exerciseNames: [
      'DB Split Squat',
      'Leg Press + Leg Machines',
      'Lat Pulldown',
      'Seated Cable Row',
      'Cable Woodchops',
      'Plank with Row',
      'Cable Face Pulls',
      'Bicep Curls',
      'Single-Leg Bridge',
      'Reverse Crunch',
    ],
  },
  {
    id: 'P3-C',
    name: 'Workout C: Shoulders (P3)',
    exerciseNames: [
      'KB Deadlift',
      'Hamstring Curl',
      'DB Overhead Press',
      'Cable/Band Lateral Raise',
      'Hanging Leg Raises',
      'Landmine Rotation',
      'Burpee DB Press',
      'Diamond + Wide Pushups',
      'Wall Sits (Weighted)',
      'Windshields/Alternate Knee Raises',
    ],
  },
  {
    id: 'P3-D',
    name: 'Workout D: Total Body (P3)',
    exerciseNames: [
      'DB Step-ups',
      'Goblet Lateral Lunge',
      'DB Renegade Row',
      'Push-up (Weighted)',
      'Medicine Ball Rotational Toss',
      'Suitcase Carry (L/R)',
      'Hammer Curl',
      'Box Dips (Assist)',
      'Lunge with Twist',
      "Farmer's Walk",
    ],
  },
  {
    id: 'Abs-A',
    name: 'Abs: Variation A',
    exerciseNames: [
      'Center Decline',
      'Teapots',
      'Single Leg Decline',
      'Knee/Leg Raises',
      'Plank',
      'Plank Shoulder Taps',
      'Deadbugs',
      'Plank In and Outs',
      'Decline Russian Twists',
      'Knee to Elbows',
      'Toe Taps',
      'V-Ups',
    ],
  },
  {
    id: 'Abs-B',
    name: 'Abs: Variation B',
    exerciseNames: [
      'V-Ups',
      'Toe Taps',
      'Knee to Elbows',
      'Decline Russian Twists',
      'Plank In and Outs',
      'Deadbugs',
      'Plank Shoulder Taps',
      'Plank',
      'Knee/Leg Raises',
      'Single Leg Decline',
      'Teapots',
      'Center Decline',
    ],
  },
  {
    id: 'Abs-C',
    name: 'Abs: Variation C',
    exerciseNames: [
      'Plank',
      'Deadbugs',
      'V-Ups',
      'Center Decline',
      'Teapots',
      'Single Leg Decline',
      'Knee/Leg Raises',
      'Plank Shoulder Taps',
      'Plank In and Outs',
      'Decline Russian Twists',
      'Knee to Elbows',
      'Toe Taps',
    ],
  },
  {
    id: 'Abs-D',
    name: 'Abs: Variation D',
    exerciseNames: [
      'Decline Russian Twists',
      'Knee to Elbows',
      'Toe Taps',
      'V-Ups',
      'Center Decline',
      'Teapots',
      'Single Leg Decline',
      'Knee/Leg Raises',
      'Plank',
      'Plank Shoulder Taps',
      'Deadbugs',
      'Plank In and Outs',
    ],
  },
];
