// ============================================================
// Workout Templates — sourced from workout_templates.csv
// Structured as static data; exercise names are matched
// against the live exercises table when a template is loaded.
// ============================================================

export type WorkoutTemplate = {
  id: string;
  phase: string;          // 'Phase 1' | 'Phase 2' | 'Phase 3' | 'Abs'
  name: string;
  category: 'Main' | 'Abs';
  exerciseNames: string[];
};

export const WORKOUT_TEMPLATES: WorkoutTemplate[] = [
  // ── Phase 1 ──────────────────────────────────────────────
  {
    id: 'P1-A',
    phase: 'Phase 1',
    name: 'Workout A: Push Focus',
    category: 'Main',
    exerciseNames: [
      'Air Squat',
      'Glute Bridge',
      'Incline Push-up',
      'Floor Press + Mod Push-up',
      'Dips',
      'Plank (Variations)',
      'Mountain Climbers + Air Squats',
      'Cobra Stretch',
      'Bear Crawl',
      'Glute Bridge Hold',
    ],
  },
  {
    id: 'P1-B',
    phase: 'Phase 1',
    name: 'Workout B: Pull Focus',
    category: 'Main',
    exerciseNames: [
      'Reverse Lunge',
      'Single-Leg Reach (Bulg Squat)',
      'Pull up/Lat Pulldown',
      'Mid Row',
      'RDL',
      'Cable Pullover',
      'Towel Curls',
      'Hammer Curl',
      'Bear Crawl',
      'Glute Bridge (Pulsing)',
    ],
  },
  {
    id: 'P1-C',
    phase: 'Phase 1',
    name: 'Workout C: Stability',
    category: 'Main',
    exerciseNames: [
      'Box Squat',
      'Step-ups/Weighted',
      'Landmine',
      'Squat Press (DB/Bar)',
      'Cable Squat Row',
      'Cable Torso Rotations',
      'Scapular Push-ups',
      'Scapular Pull-up',
      'Plank Taps',
      'BW Back Extensions',
    ],
  },
  {
    id: 'P1-D',
    phase: 'Phase 1',
    name: 'Workout D: Lateral/Total',
    category: 'Main',
    exerciseNames: [
      'Lateral Lunge',
      'Wall Sit',
      'Plank-to-Pushup',
      'Box Jump',
      'Side Planks',
      'Ball Squat Toss',
      'Single-Leg Step-Up',
      'Hip Circles',
      'Mountain Climbers',
      'In-Out Jumping Jacks',
    ],
  },

  // ── Phase 2 ──────────────────────────────────────────────
  {
    id: 'P2-A',
    phase: 'Phase 2',
    name: 'Workout A: Push Focus',
    category: 'Main',
    exerciseNames: [
      'Skater Jumps',
      'Jump Squats',
      'Tempo Push-ups',
      'Chest Pass (Med Ball)',
      'Plank Jacks',
      'Flutter Kicks',
      'T-Pushups',
      'High Knees (s)',
      'Box Jump',
      'Deadbug (Weighted)',
    ],
  },
  {
    id: 'P2-B',
    phase: 'Phase 2',
    name: 'Workout B: Pull Focus',
    category: 'Main',
    exerciseNames: [
      'Box Step-ups',
      'Walking Lunges',
      'Chin-up Negatives',
      'Med Ball Slams',
      'Mountain Climbers',
      'Bicycle Crunches',
      'Cable Face Pulls',
      'Butt Kicks (s)',
      'Single-Leg Hops',
      'Plank (Weighted)',
    ],
  },
  {
    id: 'P2-C',
    phase: 'Phase 2',
    name: 'Workout C: Shoulder Focus',
    category: 'Main',
    exerciseNames: [
      'Rope Ladder Broad Jumps',
      'Lateral Bounds',
      'Med Ball Overhead Hold',
      'Wall Balls',
      'Russian Twists',
      'Static Squat Cable Torso Rotations',
      'Pike Push-ups',
      'Jumping Jacks (s)',
      'Pilates Squat + Squat',
      'Side Plank Dips',
    ],
  },
  {
    id: 'P2-D',
    phase: 'Phase 2',
    name: 'Workout D: Agility/Total',
    category: 'Main',
    exerciseNames: [
      'Shuttle Runs (yd)',
      'Speed Skaters',
      'V-Ups/Knee Raises',
      'Burpees',
      'Spiderman Push-ups',
      'Plank with Knee-to-Elbow',
      'Mountain Climber Burpee',
      'Ice Skater Steps',
      'Squat Thrusts',
      'Deadlift',
    ],
  },

  // ── Phase 3 ──────────────────────────────────────────────
  {
    id: 'P3-A',
    phase: 'Phase 3',
    name: 'Workout A: Chest/Push',
    category: 'Main',
    exerciseNames: [
      'DB Goblet Squat',
      'RDL (Dumbbells)',
      'DB Bench Press',
      'DB Incline Press',
      'Deadbug (Weighted)',
      'Pallof Press',
      'Dips/Band Flyes',
      'Inchworm Push-Up',
      'Calf Raise',
      'Weighted Sit-up',
    ],
  },
  {
    id: 'P3-B',
    phase: 'Phase 3',
    name: 'Workout B: Back/Pull',
    category: 'Main',
    exerciseNames: [
      'DB Split Squat',
      'Leg Press + Leg Machines',
      'Lat Pulldown',
      'Seated Cable Row',
      'Cable Woodchops',
      'Plank with Row',
      'Cable Face Pulls',
      'Bicep Curls',
      'Single-Leg Bridge',
      'Reverse Crunch',
    ],
  },
  {
    id: 'P3-C',
    phase: 'Phase 3',
    name: 'Workout C: Shoulders',
    category: 'Main',
    exerciseNames: [
      'KB Deadlift',
      'Hamstring Curl',
      'DB Overhead Press',
      'Cable/Band Lateral Raise',
      'Hanging Leg Raises',
      'Landmine Rotation',
      'Burpee DB Press',
      'Diamond + Wide Pushups',
      'Wall Sits (Weighted)',
      'Windshields/Alternate Knee Raises',
    ],
  },
  {
    id: 'P3-D',
    phase: 'Phase 3',
    name: 'Workout D: Total Body',
    category: 'Main',
    exerciseNames: [
      'DB Step-ups',
      'Goblet Lateral Lunge',
      'DB Renegade Row',
      'Push-up (Weighted)',
      'Medicine Ball Rotational Toss',
      'Suitcase Carry (L/R)',
      'Hammer Curl',
      'Box Dips (Assist)',
      'Lunge with Twist',
      "Farmer's Walk",
    ],
  },

  // ── Abs ──────────────────────────────────────────────────
  {
    id: 'Abs-A',
    phase: 'Abs',
    name: 'Abs: Variation A',
    category: 'Abs',
    exerciseNames: [
      'Center Decline',
      'Teapots',
      'Single Leg Decline',
      'Knee/Leg Raises',
      'Plank',
      'Plank Shoulder Taps',
      'Deadbugs',
      'Plank In and Outs',
      'Decline Russian Twists',
      'Knee to Elbows',
      'Toe Taps',
      'V-Ups',
    ],
  },
  {
    id: 'Abs-B',
    phase: 'Abs',
    name: 'Abs: Variation B',
    category: 'Abs',
    exerciseNames: [
      'V-Ups',
      'Toe Taps',
      'Knee to Elbows',
      'Decline Russian Twists',
      'Plank In and Outs',
      'Deadbugs',
      'Plank Shoulder Taps',
      'Plank',
      'Knee/Leg Raises',
      'Single Leg Decline',
      'Teapots',
      'Center Decline',
    ],
  },
  {
    id: 'Abs-C',
    phase: 'Abs',
    name: 'Abs: Variation C',
    category: 'Abs',
    exerciseNames: [
      'Plank',
      'Deadbugs',
      'V-Ups',
      'Center Decline',
      'Teapots',
      'Single Leg Decline',
      'Knee/Leg Raises',
      'Plank Shoulder Taps',
      'Plank In and Outs',
      'Decline Russian Twists',
      'Knee to Elbows',
      'Toe Taps',
    ],
  },
  {
    id: 'Abs-D',
    phase: 'Abs',
    name: 'Abs: Variation D',
    category: 'Abs',
    exerciseNames: [
      'Decline Russian Twists',
      'Knee to Elbows',
      'Toe Taps',
      'V-Ups',
      'Center Decline',
      'Teapots',
      'Single Leg Decline',
      'Knee/Leg Raises',
      'Plank',
      'Plank Shoulder Taps',
      'Deadbugs',
      'Plank In and Outs',
    ],
  },
];

// Group templates by phase for display
export const TEMPLATE_PHASES = ['Phase 1', 'Phase 2', 'Phase 3', 'Abs'] as const;
export type TemplatePhase = (typeof TEMPLATE_PHASES)[number];

export function getTemplatesByPhase(phase: TemplatePhase): WorkoutTemplate[] {
  return WORKOUT_TEMPLATES.filter((t) => t.phase === phase);
}
