services:
  - type: web
    name: thirty60track
    env: static
    buildCommand: npx expo export --platform web
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
