/**
 * exerciseVariants.ts
 *
 * Generated by cross-referencing our seeded exercise library against the
 * free-exercise-db (yuhonas/free-exercise-db, 873 exercises, 873 image sets).
 *
 * All slugs are verified to have /exercises/{slug}/0.jpg on disk.
 * Approximations are mapped exercises whose movement pattern is semantically
 * different from our exercise name — they show a disclaimer in the UI.
 */

/**
 * Exercises whose form images are sourced from a DB exercise with a
 * genuinely different movement pattern (i.e. we used a visual approximation
 * because no exact DB match exists).
 * These receive a disclaimer in the exercise detail screen, e.g.
 * "Images shown are for a similar exercise."
 */
export const APPROXIMATED_EXERCISES = new Set<string>([
  // Cardio / full-body — mapped to a different cardio movement
  'Burpees',                          // → Mountain_Climbers  (different pattern)
  'Mountain Climbers + Air Squats',   // → Mountain_Climbers  (compound name, base only)
  'Mountain Climber Burpee',          // → Mountain_Climbers  (not a true burpee)
  'High Knees (s)',                   // → Running_Treadmill  (different movement)
  'Shuttle Runs (yd)',                // → Running_Treadmill  (different context)
  'In-Out Jumping Jacks',             // → Rope_Jumping       (different movement)
  'Jumping Jacks (s)',                // → Rope_Jumping       (different movement)
  'Rope Ladder Broad Jumps',          // → Lateral_Box_Jump   (different movement)
  'Squat Thrusts',                    // → Squat_Jerk         (different movement)
  'Butt Kicks (s)',                   // → Double_Leg_Butt_Kick (timed cue vs exercise)
  // Legs — mapped to a different leg movement
  'Wall Sit',                         // → Bodyweight_Squat   (isometric vs dynamic)
  'Wall Sits (Weighted)',             // → Bodyweight_Squat   (isometric vs dynamic)
  'Air Squat',                        // → Bodyweight_Squat   (same pattern, different name — borderline)
  'Pilates Squat + Squat',            // → Bodyweight_Squat   (Pilates variant, approximation)
  'Goblet Lateral Lunge',             // → Goblet_Squat       (lateral lunge ≠ goblet squat)
  'Squat Press (DB/Bar)',             // → Dumbbell_Squat     (press component missing)
  'Single-Leg Reach (Bulg Squat)',    // → Split_Squats       (Bulgarian variant, close)
  // Core — mapped to a different core movement
  'Plank Taps',                       // → Plank              (tapping variant → base)
  'Plank-to-Pushup',                  // → Plank              (combination → base)
  'Plank with Knee-to-Elbow',         // → Plank              (dynamic variant → base)
  'Plank (Weighted)',                 // → Plank              (loaded variant → base)
  'Plank with Row',                   // → Plank              (combination → base)
  'Plank Shoulder Taps',              // → Plank              (variant → base)
  'Plank In and Outs',                // → Plank              (dynamic variant → base)
  'Plank Jacks',                      // → Plank              (plyometric variant → base)
  'Plank (Variations)',               // → Plank              (catch-all → base)
  'Side Planks',                      // → Push_Up_to_Side_Plank (different entry point)
  'Side Plank Dips',                  // → Push_Up_to_Side_Plank (different movement)
  'Decline Russian Twists',           // → Russian_Twist      (decline variant → base)
  'V-Ups/Knee Raises',                // → Jackknife_Sit-Up   (compound name → base)
  'Windshields/Alternate Knee Raises',// → Flutter_Kicks      (windshield ≠ flutter kick)
  'Center Decline',                   // → Decline_Crunch     (custom name → approximate)
  'Single Leg Decline',               // → Decline_Crunch     (single-leg variant → base)
  'Knee/Leg Raises',                  // → Hanging_Leg_Raise  (floor raises ≠ hanging)
  'Knee to Elbows',                   // → Hanging_Leg_Raise  (may be floor variation)
  'Toe Taps',                         // → Toe_Touchers       (slightly different form)
  // Push — mapped to different push pattern
  'Spiderman Push-ups',               // → Spider_Crawl       (different movement entirely)
  'Scapular Push-ups',                // → Scapular_Pull-Up   (push vs pull — opposite)
  'Pike Push-ups',                    // → Handstand_Push-Ups (approximate — no true pike entry)
  'T-Pushups',                        // → Push_Up_to_Side_Plank (close but not identical)
  'Diamond + Wide Pushups',           // → Pushups            (combined width variant → base)
  'Tempo Push-ups',                   // → Pushups            (same movement, tempo cue)
  'Push-up (Weighted)',               // → Pushups            (weighted variant → base)
  'Floor Press + Mod Push-up',        // → Floor_Press        (compound — press + push-up)
  'Burpee DB Press',                  // → Pushups            (compound — burpee component missing)
  // Pull / back
  'Cable Squat Row',                  // → Seated_Cable_Rows  (squat component missing)
  'Pull up/Lat Pulldown',             // → Pullups            (catch-all name)
  'Cable Pullover',                   // → Cable_Crossover    (pullover ≠ crossover)
  'Chin-up Negatives',                // → Chin-Up            (eccentric-only → full movement)
  // Full body / carries
  'Suitcase Carry (L/R)',             // → Farmers_Walk       (single-arm vs double)
  'Bear Crawl',                       // → Bear_Crawl_Sled_Drags (sled version in DB)
  'Ball Squat Toss',                  // → Medicine_Ball_Chest_Pass (squat component missing)
  'Med Ball Overhead Hold',           // → Medicine_Ball_Scoop_Throw (static hold ≠ throw)
  'Wall Balls',                       // → Backward_Medicine_Ball_Throw (wall throw variant)
  'Inchworm Push-Up',                 // → Inchworm           (push-up component not in DB entry)
  'KB Deadlift',                      // → Kettlebell_Dead_Clean (clean component added)
  // Flexibility
  'Cobra Stretch',                    // → Cat_Stretch        (different stretch entirely)
  // Legs additional
  'Lunge with Twist',                 // → Dumbbell_Lunges    (twist component missing)
  'Lateral Lunge',                    // → Dumbbell_Lunges    (lateral ≠ forward lunge)
  'Static Squat Cable Torso Rotations',// → Torso_Rotation    (squat context not shown)
  'Cable Torso Rotations',            // → Torso_Rotation     (cable context may differ)
]);

/**
 * Maps our exercise names to an array of verified DB variant slugs.
 * The first slug is always the primary (from SLUG_OVERRIDES or auto-slug).
 * Only exercises with 2 or more verified variants are included.
 * All slugs have been verified to have /exercises/{slug}/0.jpg on disk.
 *
 * Display names are derived from slugs: underscores → spaces, equipment
 * prefixes removed where redundant.
 */
export const EXERCISE_VARIANTS: Record<string, string[]> = {
  // ── CHEST ──────────────────────────────────────────────────────────────────

  'Bench Press': [
    'Barbell_Bench_Press_-_Medium_Grip',       // primary
    'Bench_Press_-_Powerlifting',
    'Bench_Press_-_With_Bands',
    'Bench_Press_with_Chains',
    'Close-Grip_Barbell_Bench_Press',
    'Decline_Barbell_Bench_Press',
    'Decline_Dumbbell_Bench_Press',
    'Dumbbell_Bench_Press',
    'Dumbbell_Bench_Press_with_Neutral_Grip',
    'Machine_Bench_Press',
    'One_Arm_Dumbbell_Bench_Press',
    'Reverse_Band_Bench_Press',
    'Reverse_Triceps_Bench_Press',
    'Smith_Machine_Bench_Press',
    'Smith_Machine_Close-Grip_Bench_Press',
    'Wide-Grip_Barbell_Bench_Press',
    'Wide-Grip_Decline_Barbell_Bench_Press',
  ],

  'Incline Bench Press': [
    'Barbell_Incline_Bench_Press_-_Medium_Grip', // primary
    'Hammer_Grip_Incline_DB_Bench_Press',
    'Incline_Dumbbell_Bench_With_Palms_Facing_In',
    'Incline_Dumbbell_Press',
    'Smith_Machine_Incline_Bench_Press',
  ],

  'Push-Up': [
    'Pushups',                                  // primary
    'Close-Grip_Push-Up_off_of_a_Dumbbell',
    'Decline_Push-Up',
    'Incline_Push-Up',
    'Plyo_Push-up',
    'Push-Up_Wide',
    'Push-Ups_-_Close_Triceps_Position',
    'Push-Ups_With_Feet_Elevated',
    'Push-Ups_With_Feet_On_An_Exercise_Ball',
    'Push_Up_to_Side_Plank',
    'Single-Arm_Push-Up',
  ],

  'Cable Fly': [
    'Flat_Bench_Cable_Flyes',                   // primary
    'Cable_Crossover',
    'Incline_Cable_Flye',
    'Low_Cable_Crossover',
    'Single-Arm_Cable_Crossover',
  ],

  'DB Bench Press': [
    'Dumbbell_Bench_Press',                     // primary
    'Dumbbell_Bench_Press_with_Neutral_Grip',
    'Hammer_Grip_Incline_DB_Bench_Press',
    'One_Arm_Dumbbell_Bench_Press',
  ],

  'DB Incline Press': [
    'Incline_Dumbbell_Press',                   // primary
    'Hammer_Grip_Incline_DB_Bench_Press',
    'Incline_Dumbbell_Bench_With_Palms_Facing_In',
    'Incline_Dumbbell_Flyes',
  ],

  'Dips': [
    'Dips_-_Chest_Version',                     // primary
    'Bench_Dips',
    'Dips_-_Triceps_Version',
    'Ring_Dips',
  ],

  'Dips/Band Flyes': [
    'Dumbbell_Flyes',                           // primary
    'Decline_Dumbbell_Flyes',
    'Incline_Dumbbell_Flyes',
    'One-Arm_Flat_Bench_Dumbbell_Flye',
  ],

  'Floor Press + Mod Push-up': [
    'Floor_Press',                              // primary
    'Alternating_Floor_Press',
    'Dumbbell_Floor_Press',
    'Floor_Press_with_Chains',
    'One_Arm_Floor_Press',
  ],

  // ── BACK ──────────────────────────────────────────────────────────────────

  'Deadlift': [
    'Barbell_Deadlift',                         // primary
    'Axle_Deadlift',
    'Cable_Deadlifts',
    'Clean_Deadlift',
    'Deadlift_with_Bands',
    'Deadlift_with_Chains',
    'Deficit_Deadlift',
    'Kettlebell_One-Legged_Deadlift',
    'Reverse_Band_Deadlift',
    'Romanian_Deadlift',
    'Snatch_Deadlift',
    'Stiff-Legged_Barbell_Deadlift',
    'Stiff-Legged_Dumbbell_Deadlift',
    'Sumo_Deadlift',
    'Sumo_Deadlift_with_Bands',
    'Trap_Bar_Deadlift',
  ],

  'Barbell Row': [
    'Bent_Over_Barbell_Row',                    // primary
    'Lying_Cambered_Barbell_Row',
    'Smith_Machine_Bent_Over_Row',
    'Upright_Barbell_Row',
  ],

  'Pull-Up': [
    'Pullups',                                  // primary
    'Band_Assisted_Pull-Up',
    'Chin-Up',
    'One_Arm_Chin-Up',
    'Rocky_Pull-Ups_Pulldowns',
    'Scapular_Pull-Up',
    'V-Bar_Pullup',
    'Wide-Grip_Rear_Pull-Up',
  ],

  'Lat Pulldown': [
    'Wide-Grip_Lat_Pulldown',                   // primary
    'Close-Grip_Front_Lat_Pulldown',
    'Full_Range-Of-Motion_Lat_Pulldown',
    'One_Arm_Lat_Pulldown',
  ],

  'Seated Cable Row': [
    'Seated_Cable_Rows',                        // primary
    'Elevated_Cable_Rows',
    'Upright_Cable_Row',
  ],

  'BW Back Extensions': [
    'Hyperextensions_Back_Extensions',          // primary
    'Hyperextensions_With_No_Hyperextension_Bench',
    'Reverse_Hyperextension',
    'Weighted_Ball_Hyperextension',
  ],

  'Mid Row': [
    'Bodyweight_Mid_Row',                       // primary
    'Straight_Bar_Bench_Mid_Rows',
  ],

  // ── SHOULDERS ────────────────────────────────────────────────────────────

  'Overhead Press': [
    'Barbell_Shoulder_Press',                   // primary
    'Cable_Shoulder_Press',
    'Dumbbell_Shoulder_Press',
    'Dumbbell_One-Arm_Shoulder_Press',
    'Seated_Barbell_Military_Press',
    'Seated_Cable_Shoulder_Press',
    'Smith_Machine_Overhead_Shoulder_Press',
    'Standing_Military_Press',
  ],

  'Lateral Raise': [
    'Side_Lateral_Raise',                       // primary
    'Cable_Seated_Lateral_Raise',
    'Lateral_Raise_-_With_Bands',
    'Lying_One-Arm_Lateral_Raise',
    'Seated_Side_Lateral_Raise',
  ],

  'DB Overhead Press': [
    'Dumbbell_Shoulder_Press',                  // primary
    'Dumbbell_One-Arm_Shoulder_Press',
    'Cable_Shoulder_Press',
  ],

  'Cable/Band Lateral Raise': [
    'Cable_Seated_Lateral_Raise',               // primary
    'Lateral_Raise_-_With_Bands',
    'Seated_Side_Lateral_Raise',
    'Side_Lateral_Raise',
  ],

  'Pike Push-ups': [
    'Handstand_Push-Ups',                       // primary (approximation)
    'Hanging_Pike',
  ],

  // ── ARMS ──────────────────────────────────────────────────────────────────

  'Barbell Curl': [
    'Barbell_Curl',                             // primary
    'Barbell_Curls_Lying_Against_An_Incline',
    'Close-Grip_EZ_Bar_Curl',
    'Close-Grip_EZ-Bar_Curl_with_Band',
    'Close-Grip_Standing_Barbell_Curl',
    'EZ-Bar_Curl',
    'Reverse_Barbell_Curl',
    'Wide-Grip_Standing_Barbell_Curl',
  ],

  'Tricep Pushdown': [
    'Triceps_Pushdown',                         // primary
    'Reverse_Grip_Triceps_Pushdown',
    'Triceps_Pushdown_-_Rope_Attachment',
    'Triceps_Pushdown_-_V-Bar_Attachment',
  ],

  'Hammer Curl': [
    'Hammer_Curls',                             // primary
    'Alternate_Hammer_Curl',
    'Cable_Hammer_Curls_-_Rope_Attachment',
    'Cross_Body_Hammer_Curl',
    'Incline_Hammer_Curls',
  ],

  'Skull Crusher': [
    'EZ-Bar_Skullcrusher',                      // primary
    'Band_Skull_Crusher',
    'Decline_Close-Grip_Bench_To_Skull_Crusher',
  ],

  'Bicep Curls': [
    'Dumbbell_Bicep_Curl',                      // primary
    'Alternate_Hammer_Curl',
    'Incline_Dumbbell_Curl',
    'Lying_Supine_Dumbbell_Curl',
    'Seated_Dumbbell_Curl',
  ],

  'Towel Curls': [
    'Hammer_Curls',                             // primary (approximation)
    'Alternate_Hammer_Curl',
    'Cable_Hammer_Curls_-_Rope_Attachment',
    'Cross_Body_Hammer_Curl',
    'Incline_Hammer_Curls',
  ],

  'Box Dips (Assist)': [
    'Bench_Dips',                               // primary
    'Weighted_Bench_Dip',
  ],

  // ── LEGS ──────────────────────────────────────────────────────────────────

  'Squat': [
    'Barbell_Full_Squat',                       // primary
    'Barbell_Hack_Squat',
    'Barbell_Squat',
    'Barbell_Squat_To_A_Bench',
    'Bodyweight_Squat',
    'Box_Squat',
    'Dumbbell_Squat',
    'Front_Barbell_Squat',
    'Goblet_Squat',
    'Hack_Squat',
    'Olympic_Squat',
    'Overhead_Squat',
    'Smith_Machine_Squat',
    'Squat_with_Bands',
    'Squat_with_Chains',
    'Wide_Stance_Barbell_Squat',
    'Weighted_Squat',
    'Zercher_Squats',
  ],

  'Romanian Deadlift': [
    'Romanian_Deadlift',                        // primary
    'Romanian_Deadlift_from_Deficit',
    'Smith_Machine_Stiff-Legged_Deadlift',
    'Stiff-Legged_Barbell_Deadlift',
    'Stiff-Legged_Dumbbell_Deadlift',
  ],

  'RDL': [
    'Romanian_Deadlift',                        // primary
    'Romanian_Deadlift_from_Deficit',
    'Stiff-Legged_Barbell_Deadlift',
    'Stiff-Legged_Dumbbell_Deadlift',
  ],

  'RDL (Dumbbells)': [
    'Stiff-Legged_Dumbbell_Deadlift',           // primary
    'Romanian_Deadlift',
    'Romanian_Deadlift_from_Deficit',
    'Smith_Machine_Stiff-Legged_Deadlift',
    'Stiff-Legged_Barbell_Deadlift',
  ],

  'Leg Press': [
    'Leg_Press',                                // primary
    'Narrow_Stance_Leg_Press',
    'Smith_Machine_Leg_Press',
  ],

  'Leg Curl': [
    'Lying_Leg_Curls',                          // primary
    'Ball_Leg_Curl',
    'Seated_Leg_Curl',
    'Standing_Leg_Curl',
  ],

  'Hamstring Curl': [
    'Lying_Leg_Curls',                          // primary
    'Ball_Leg_Curl',
    'Seated_Band_Hamstring_Curl',
    'Seated_Leg_Curl',
    'Standing_Leg_Curl',
  ],

  'Leg Extension': [
    'Leg_Extensions',                           // primary
    'Single-Leg_Leg_Extension',
  ],

  'Calf Raise': [
    'Seated_Calf_Raise',                        // primary
    'Donkey_Calf_Raises',
    'Smith_Machine_Calf_Raise',
    'Standing_Barbell_Calf_Raise',
    'Standing_Calf_Raises',
    'Standing_Dumbbell_Calf_Raise',
  ],

  'Lunges': [
    'Dumbbell_Lunges',                          // primary
    'Barbell_Lunge',
    'Barbell_Walking_Lunge',
    'Bodyweight_Walking_Lunge',
    'Crossover_Reverse_Lunge',
    'Dumbbell_Rear_Lunge',
    'Elevated_Back_Lunge',
  ],

  'Reverse Lunge': [
    'Dumbbell_Rear_Lunge',                      // primary
    'Crossover_Reverse_Lunge',
    'Dumbbell_Lunges',
    'Elevated_Back_Lunge',
  ],

  'Walking Lunges': [
    'Bodyweight_Walking_Lunge',                 // primary
    'Barbell_Walking_Lunge',
    'Dumbbell_Lunges',
  ],

  'Box Squat': [
    'Box_Squat',                                // primary
    'Box_Squat_with_Bands',
    'Box_Squat_with_Chains',
    'Reverse_Band_Box_Squat',
    'Single-Leg_High_Box_Squat',
    'Speed_Box_Squat',
  ],

  'DB Split Squat': [
    'Split_Squat_with_Dumbbells',               // primary
    'Barbell_Side_Split_Squat',
    'Smith_Single-Leg_Split_Squat',
    'Split_Squats',
    'Suspended_Split_Squat',
  ],

  'DB Goblet Squat': [
    'Goblet_Squat',                             // primary
    'Dumbbell_Squat',
    'Front_Barbell_Squat',
  ],

  'Box Jump': [
    'Front_Box_Jump',                           // primary
    'Box_Jump_Multiple_Response',
    'Dumbbell_Seated_Box_Jump',
    'Lateral_Box_Jump',
  ],

  'Jump Squats': [
    'Freehand_Jump_Squat',                      // primary
    'Kneeling_Jump_Squat',
    'Weighted_Jump_Squat',
  ],

  'DB Step-ups': [
    'Dumbbell_Step_Ups',                        // primary
    'Barbell_Step_Ups',
    'Step-up_with_Knee_Raise',
  ],

  'Step-ups/Weighted': [
    'Dumbbell_Step_Ups',                        // primary
    'Barbell_Step_Ups',
    'Step-up_with_Knee_Raise',
  ],

  'Box Step-ups': [
    'Dumbbell_Step_Ups',                        // primary
    'Barbell_Step_Ups',
    'Step-up_with_Knee_Raise',
  ],

  'Glute Bridge': [
    'Barbell_Glute_Bridge',                     // primary
    'Barbell_Hip_Thrust',
    'Single_Leg_Glute_Bridge',
  ],

  'Glute Bridge Hold': [
    'Barbell_Glute_Bridge',                     // primary
    'Barbell_Hip_Thrust',
    'Single_Leg_Glute_Bridge',
  ],

  'Glute Bridge (Pulsing)': [
    'Barbell_Glute_Bridge',                     // primary
    'Barbell_Hip_Thrust',
    'Single_Leg_Glute_Bridge',
  ],

  'Butt Kicks (s)': [
    'Double_Leg_Butt_Kick',                     // primary (approximation)
    'Single_Leg_Butt_Kick',
  ],

  'Rope Ladder Broad Jumps': [
    'Lateral_Box_Jump',                         // primary (approximation)
    'Box_Jump_Multiple_Response',
    'Front_Box_Jump',
  ],

  // ── CORE ──────────────────────────────────────────────────────────────────

  'Crunch': [
    'Crunches',                                 // primary
    'Cross-Body_Crunch',
    'Decline_Crunch',
    'Decline_Oblique_Crunch',
    'Decline_Reverse_Crunch',
    'Reverse_Crunch',
    'Weighted_Crunches',
  ],

  'Cable Crunch': [
    'Cable_Crunch',                             // primary
    'Bosu_Ball_Cable_Crunch_With_Side_Bends',
    'Cable_Seated_Crunch',
    'Kneeling_Cable_Crunch_With_Alternating_Oblique_Twists',
    'Rope_Crunch',
    'Standing_Rope_Crunch',
  ],

  'Reverse Crunch': [
    'Reverse_Crunch',                           // primary
    'Cable_Reverse_Crunch',
    'Decline_Reverse_Crunch',
    'Suspended_Reverse_Crunch',
  ],

  'Plank': [
    'Plank',                                    // primary
    'Push_Up_to_Side_Plank',
  ],

  'Russian Twists': [
    'Russian_Twist',                            // primary
    'Cable_Russian_Twists',
  ],

  'Decline Russian Twists': [
    'Russian_Twist',                            // primary (approximation)
    'Cable_Russian_Twists',
  ],

  'V-Ups': [
    'Jackknife_Sit-Up',                         // primary
    'Side_Jackknife',
  ],

  'V-Ups/Knee Raises': [
    'Jackknife_Sit-Up',                         // primary (approximation)
    'Side_Jackknife',
  ],

  'Pallof Press': [
    'Pallof_Press',                             // primary
    'Pallof_Press_With_Rotation',
  ],

  'Hanging Leg Raises': [
    'Hanging_Leg_Raise',                        // primary
    'Hanging_Pike',
  ],

  'Center Decline': [
    'Decline_Crunch',                           // primary (approximation)
    'Decline_Oblique_Crunch',
  ],

  'Single Leg Decline': [
    'Decline_Crunch',                           // primary (approximation)
    'Decline_Oblique_Crunch',
    'Decline_Reverse_Crunch',
  ],

  'Teapots': [
    'Dumbbell_Side_Bend',                       // primary
    'Barbell_Side_Bend',
  ],

  'Medicine Ball Rotational Toss': [
    'Medicine_Ball_Scoop_Throw',                // primary
    'Backward_Medicine_Ball_Throw',
    'Medicine_Ball_Chest_Pass',
    'Medicine_Ball_Full_Twist',
    'One-Arm_Medicine_Ball_Slam',
  ],

  // ── FULL BODY / COMPOUND ──────────────────────────────────────────────────

  'Landmine': [
    'Landmine_180s',                            // primary
    'Landmine_Linear_Jammer',
  ],

  'Landmine Rotation': [
    'Landmine_180s',                            // primary
    'Landmine_Linear_Jammer',
  ],

  'Med Ball Slams': [
    'Overhead_Slam',                            // primary
    'One-Arm_Medicine_Ball_Slam',
  ],

  'Suitcase Carry (L/R)': [
    'Farmers_Walk',                             // primary (approximation)
    'Rickshaw_Carry',
  ],

  "Farmer's Walk": [
    'Farmers_Walk',                             // primary
    'Rickshaw_Carry',
  ],

  'Hip Circles': [
    'Hip_Circles_prone',                        // primary
    'Standing_Hip_Circles',
  ],

  // ── CARDIO ────────────────────────────────────────────────────────────────

  'Treadmill Run': [
    'Running_Treadmill',                        // primary
    'Jogging_Treadmill',
    'Trail_Running_Walking',
    'Walking_Treadmill',
  ],

  'Cycling': [
    'Bicycling',                                // primary
    'Air_Bike',
    'Bicycling_Stationary',
    'Recumbent_Bike',
  ],
};
